import * as mongoose from 'mongoose';

export const MetricSchema = new mongoose.Schema({
    metric: {
        '10DayAverageTradingVolume': mongoose.Schema.Types.Mixed,
        '13WeekPriceReturnDaily': mongoose.Schema.Types.Mixed,
        '26WeekPriceReturnDaily': mongoose.Schema.Types.Mixed,
        '3MonthAverageTradingVolume': mongoose.Schema.Types.Mixed,
        '52WeekHigh': mongoose.Schema.Types.Mixed,
        '52WeekHighDate': String,
        '52WeekLow': mongoose.Schema.Types.Mixed,
        '52WeekLowDate': String,
        '52WeekPriceReturnDaily': mongoose.Schema.Types.Mixed,
        '5DayPriceReturnDaily': mongoose.Schema.Types.Mixed,
        assetTurnoverAnnual: mongoose.Schema.Types.Mixed,
        assetTurnoverTTM: mongoose.Schema.Types.Mixed,
        beta: mongoose.Schema.Types.Mixed,
        bookValuePerShareAnnual: mongoose.Schema.Types.Mixed,
        bookValuePerShareQuarterly: mongoose.Schema.Types.Mixed,
        bookValueShareGrowth5Y: mongoose.Schema.Types.Mixed,
        capitalSpendingGrowth5Y: mongoose.Schema.Types.Mixed,
        cashFlowPerShareAnnual: mongoose.Schema.Types.Mixed,
        cashFlowPerShareTTM: mongoose.Schema.Types.Mixed,
        cashPerSharePerShareAnnual: mongoose.Schema.Types.Mixed,
        cashPerSharePerShareQuarterly: mongoose.Schema.Types.Mixed,
        currentDividendYieldTTM: mongoose.Schema.Types.Mixed,
        'currentEv/freeCashFlowAnnual': mongoose.Schema.Types.Mixed,
        'currentEv/freeCashFlowTTM': mongoose.Schema.Types.Mixed,
        currentRatioAnnual: mongoose.Schema.Types.Mixed,
        currentRatioQuarterly: mongoose.Schema.Types.Mixed,
        dividendGrowthRate5Y: mongoose.Schema.Types.Mixed,
        dividendPerShare5Y: mongoose.Schema.Types.Mixed,
        dividendPerShareAnnual: mongoose.Schema.Types.Mixed,
        dividendYield5Y: mongoose.Schema.Types.Mixed,
        dividendYieldIndicatedAnnual: mongoose.Schema.Types.Mixed,
        dividendsPerShareTTM: mongoose.Schema.Types.Mixed,
        ebitdPerShareTTM: mongoose.Schema.Types.Mixed,
        ebitdaCagr5Y: mongoose.Schema.Types.Mixed,
        ebitdaInterimCagr5Y: mongoose.Schema.Types.Mixed,
        epsBasicExclExtraItemsAnnual: mongoose.Schema.Types.Mixed,
        epsBasicExclExtraItemsTTM: mongoose.Schema.Types.Mixed,
        epsExclExtraItemsAnnual: mongoose.Schema.Types.Mixed,
        epsExclExtraItemsTTM: mongoose.Schema.Types.Mixed,
        epsGrowth3Y: mongoose.Schema.Types.Mixed,
        epsGrowth5Y: mongoose.Schema.Types.Mixed,
        epsGrowthQuarterlyYoy: mongoose.Schema.Types.Mixed,
        epsGrowthTTMYoy: mongoose.Schema.Types.Mixed,
        epsInclExtraItemsAnnual: mongoose.Schema.Types.Mixed,
        epsInclExtraItemsTTM: mongoose.Schema.Types.Mixed,
        epsNormalizedAnnual: mongoose.Schema.Types.Mixed,
        focfCagr5Y: mongoose.Schema.Types.Mixed,
        freeCashFlowAnnual: mongoose.Schema.Types.Mixed,
        freeCashFlowPerShareTTM: mongoose.Schema.Types.Mixed,
        freeCashFlowTTM: mongoose.Schema.Types.Mixed,
        'freeOperatingCashFlow/revenue5Y': mongoose.Schema.Types.Mixed,
        'freeOperatingCashFlow/revenueTTM': mongoose.Schema.Types.Mixed,
        grossMargin5Y: mongoose.Schema.Types.Mixed,
        grossMarginAnnual: mongoose.Schema.Types.Mixed,
        grossMarginTTM: mongoose.Schema.Types.Mixed,
        inventoryTurnoverAnnual: mongoose.Schema.Types.Mixed,
        inventoryTurnoverTTM: mongoose.Schema.Types.Mixed,
        'longTermDebt/equityAnnual': mongoose.Schema.Types.Mixed,
        'longTermDebt/equityQuarterly': mongoose.Schema.Types.Mixed,
        marketCapitalization: mongoose.Schema.Types.Mixed,
        monthToDatePriceReturnDaily: mongoose.Schema.Types.Mixed,
        netDebtAnnual: mongoose.Schema.Types.Mixed,
        netDebtInterim: mongoose.Schema.Types.Mixed,
        netIncomeEmployeeAnnual: mongoose.Schema.Types.Mixed,
        netIncomeEmployeeTTM: mongoose.Schema.Types.Mixed,
        netInterestCoverageAnnual: String,
        netInterestCoverageTTM: String,
        netMarginGrowth5Y: mongoose.Schema.Types.Mixed,
        netProfitMargin5Y: mongoose.Schema.Types.Mixed,
        netProfitMarginAnnual: mongoose.Schema.Types.Mixed,
        netProfitMarginTTM: mongoose.Schema.Types.Mixed,
        operatingMargin5Y: mongoose.Schema.Types.Mixed,
        operatingMarginAnnual: mongoose.Schema.Types.Mixed,
        operatingMarginTTM: mongoose.Schema.Types.Mixed,
        payoutRatioAnnual: mongoose.Schema.Types.Mixed,
        payoutRatioTTM: mongoose.Schema.Types.Mixed,
        pbAnnual: mongoose.Schema.Types.Mixed,
        pbQuarterly: mongoose.Schema.Types.Mixed,
        pcfShareTTM: mongoose.Schema.Types.Mixed,
        peBasicExclExtraTTM: mongoose.Schema.Types.Mixed,
        peExclExtraAnnual: mongoose.Schema.Types.Mixed,
        peExclExtraHighTTM: mongoose.Schema.Types.Mixed,
        peExclExtraTTM: mongoose.Schema.Types.Mixed,
        peExclLowTTM: mongoose.Schema.Types.Mixed,
        peInclExtraTTM: mongoose.Schema.Types.Mixed,
        peNormalizedAnnual: mongoose.Schema.Types.Mixed,
        pfcfShareAnnual: mongoose.Schema.Types.Mixed,
        pfcfShareTTM: mongoose.Schema.Types.Mixed,
        pretaxMargin5Y: mongoose.Schema.Types.Mixed,
        pretaxMarginAnnual: mongoose.Schema.Types.Mixed,
        pretaxMarginTTM: mongoose.Schema.Types.Mixed,
        'priceRelativeToS&P50013Week': mongoose.Schema.Types.Mixed,
        'priceRelativeToS&P50026Week': mongoose.Schema.Types.Mixed,
        'priceRelativeToS&P5004Week': mongoose.Schema.Types.Mixed,
        'priceRelativeToS&P50052Week': mongoose.Schema.Types.Mixed,
        'priceRelativeToS&P500Ytd': mongoose.Schema.Types.Mixed,
        psAnnual: mongoose.Schema.Types.Mixed,
        psTTM: mongoose.Schema.Types.Mixed,
        ptbvAnnual: mongoose.Schema.Types.Mixed,
        ptbvQuarterly: mongoose.Schema.Types.Mixed,
        quickRatioAnnual: mongoose.Schema.Types.Mixed,
        quickRatioQuarterly: mongoose.Schema.Types.Mixed,
        receivablesTurnoverAnnual: mongoose.Schema.Types.Mixed,
        receivablesTurnoverTTM: mongoose.Schema.Types.Mixed,
        revenueEmployeeAnnual: mongoose.Schema.Types.Mixed,
        revenueEmployeeTTM: mongoose.Schema.Types.Mixed,
        revenueGrowth3Y: mongoose.Schema.Types.Mixed,
        revenueGrowth5Y: mongoose.Schema.Types.Mixed,
        revenueGrowthQuarterlyYoy: mongoose.Schema.Types.Mixed,
        revenueGrowthTTMYoy: mongoose.Schema.Types.Mixed,
        revenuePerShareAnnual: mongoose.Schema.Types.Mixed,
        revenuePerShareTTM: mongoose.Schema.Types.Mixed,
        revenueShareGrowth5Y: mongoose.Schema.Types.Mixed,
        roaRfy: mongoose.Schema.Types.Mixed,
        roaa5Y: mongoose.Schema.Types.Mixed,
        roae5Y: mongoose.Schema.Types.Mixed,
        roaeTTM: mongoose.Schema.Types.Mixed,
        roeRfy: mongoose.Schema.Types.Mixed,
        roeTTM: mongoose.Schema.Types.Mixed,
        roi5Y: mongoose.Schema.Types.Mixed,
        roiAnnual: mongoose.Schema.Types.Mixed,
        roiTTM: mongoose.Schema.Types.Mixed,
        tangibleBookValuePerShareAnnual: mongoose.Schema.Types.Mixed,
        tangibleBookValuePerShareQuarterly: mongoose.Schema.Types.Mixed,
        tbvCagr5Y: mongoose.Schema.Types.Mixed,
        'totalDebt/totalEquityAnnual': mongoose.Schema.Types.Mixed,
        'totalDebt/totalEquityQuarterly': mongoose.Schema.Types.Mixed,
        totalDebtCagr5Y: mongoose.Schema.Types.Mixed,
        yearToDatePriceReturnDaily: mongoose.Schema.Types.Mixed,
      },
      metricType: String,
      series: {
        annual: {
          cashRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          currentRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          ebitPerShare: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          eps: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          grossMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalAsset: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netDebtToTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netDebtToTotalEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          operatingMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          pretaxMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          salesPerShare: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          sgaToSale: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToTotalAsset: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
        },
        quarterly: {
          cashRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          currentRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          ebitPerShare: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          eps: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          grossMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalAsset: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          longtermDebtTotalEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netDebtToTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netDebtToTotalEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          netMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          operatingMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          pretaxMargin: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          salesPerShare: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          sgaToSale: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToEquity: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToTotalAsset: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalDebtToTotalCapital: [{ period: String, v: mongoose.Schema.Types.Mixed }],
          totalRatio: [{ period: String, v: mongoose.Schema.Types.Mixed }],
        },
      },
      symbol: String,
})
