export interface IMetric {
  metric: {
    '10DayAverageTradingVolume': number;
    '13WeekPriceReturnDaily': number;
    '26WeekPriceReturnDaily': number;
    '3MonthAverageTradingVolume': number;
    '52WeekHigh': number;
    '52WeekHighDate': string;
    '52WeekLow': number;
    '52WeekLowDate': string;
    '52WeekPriceReturnDaily': number;
    '5DayPriceReturnDaily': number;
    assetTurnoverAnnual: number;
    assetTurnoverTTM: number;
    beta: number;
    bookValuePerShareAnnual: number;
    bookValuePerShareQuarterly: number;
    bookValueShareGrowth5Y: number;
    capitalSpendingGrowth5Y: number;
    cashFlowPerShareAnnual: number;
    cashFlowPerShareTTM: number;
    cashPerSharePerShareAnnual: number;
    cashPerSharePerShareQuarterly: number;
    currentDividendYieldTTM: number;
    'currentEv/freeCashFlowAnnual': number;
    'currentEv/freeCashFlowTTM': number;
    currentRatioAnnual: number;
    currentRatioQuarterly: number;
    dividendGrowthRate5Y: number;
    dividendPerShare5Y: number;
    dividendPerShareAnnual: number;
    dividendYield5Y: number;
    dividendYieldIndicatedAnnual: number;
    dividendsPerShareTTM: number;
    ebitdPerShareTTM: number;
    ebitdaCagr5Y: number;
    ebitdaInterimCagr5Y: number;
    epsBasicExclExtraItemsAnnual: number;
    epsBasicExclExtraItemsTTM: number;
    epsExclExtraItemsAnnual: number;
    epsExclExtraItemsTTM: number;
    epsGrowth3Y: number;
    epsGrowth5Y: number;
    epsGrowthQuarterlyYoy: number;
    epsGrowthTTMYoy: number;
    epsInclExtraItemsAnnual: number;
    epsInclExtraItemsTTM: number;
    epsNormalizedAnnual: number;
    focfCagr5Y: number;
    freeCashFlowAnnual: number;
    freeCashFlowPerShareTTM: number;
    freeCashFlowTTM: number;
    'freeOperatingCashFlow/revenue5Y': number;
    'freeOperatingCashFlow/revenueTTM': number;
    grossMargin5Y: number;
    grossMarginAnnual: number;
    grossMarginTTM: number;
    inventoryTurnoverAnnual: number;
    inventoryTurnoverTTM: number;
    'longTermDebt/equityAnnual': number;
    'longTermDebt/equityQuarterly': number;
    marketCapitalization: number;
    monthToDatePriceReturnDaily: number;
    netDebtAnnual: number;
    netDebtInterim: number;
    netIncomeEmployeeAnnual: number;
    netIncomeEmployeeTTM: number;
    netInterestCoverageAnnual: string;
    netInterestCoverageTTM: string;
    netMarginGrowth5Y: number;
    netProfitMargin5Y: number;
    netProfitMarginAnnual: number;
    netProfitMarginTTM: number;
    operatingMargin5Y: number;
    operatingMarginAnnual: number;
    operatingMarginTTM: number;
    payoutRatioAnnual: number;
    payoutRatioTTM: number;
    pbAnnual: number;
    pbQuarterly: number;
    pcfShareTTM: number;
    peBasicExclExtraTTM: number;
    peExclExtraAnnual: number;
    peExclExtraHighTTM: number;
    peExclExtraTTM: number;
    peExclLowTTM: number;
    peInclExtraTTM: number;
    peNormalizedAnnual: number;
    pfcfShareAnnual: number;
    pfcfShareTTM: number;
    pretaxMargin5Y: number;
    pretaxMarginAnnual: number;
    pretaxMarginTTM: number;
    'priceRelativeToS&P50013Week': number;
    'priceRelativeToS&P50026Week': number;
    'priceRelativeToS&P5004Week': number;
    'priceRelativeToS&P50052Week': number;
    'priceRelativeToS&P500Ytd': number;
    psAnnual: number;
    psTTM: number;
    ptbvAnnual: number;
    ptbvQuarterly: number;
    quickRatioAnnual: number;
    quickRatioQuarterly: number;
    receivablesTurnoverAnnual: number;
    receivablesTurnoverTTM: number;
    revenueEmployeeAnnual: number;
    revenueEmployeeTTM: number;
    revenueGrowth3Y: number;
    revenueGrowth5Y: number;
    revenueGrowthQuarterlyYoy: number;
    revenueGrowthTTMYoy: number;
    revenuePerShareAnnual: number;
    revenuePerShareTTM: number;
    revenueShareGrowth5Y: number;
    roaRfy: number;
    roaa5Y: number;
    roae5Y: number;
    roaeTTM: number;
    roeRfy: number;
    roeTTM: number;
    roi5Y: number;
    roiAnnual: number;
    roiTTM: number;
    tangibleBookValuePerShareAnnual: number;
    tangibleBookValuePerShareQuarterly: number;
    tbvCagr5Y: number;
    'totalDebt/totalEquityAnnual': number;
    'totalDebt/totalEquityQuarterly': number;
    totalDebtCagr5Y: number;
    yearToDatePriceReturnDaily: number;
  };
  metricType: string;
  series: {
    annual: {
      cashRatio: { period: string; v: number }[];
      currentRatio: { period: string; v: number }[];
      ebitPerShare: { period: string; v: number }[];
      eps: { period: string; v: number }[];
      grossMargin: { period: string; v: number }[];
      longtermDebtTotalAsset: { period: string; v: number }[];
      longtermDebtTotalCapital: { period: string; v: number }[];
      longtermDebtTotalEquity: { period: string; v: number }[];
      netDebtToTotalCapital: { period: string; v: number }[];
      netDebtToTotalEquity: { period: string; v: number }[];
      netMargin: { period: string; v: number }[];
      operatingMargin: { period: string; v: number }[];
      pretaxMargin: { period: string; v: number }[];
      salesPerShare: { period: string; v: number }[];
      sgaToSale: { period: string; v: number }[];
      totalDebtToEquity: { period: string; v: number }[];
      totalDebtToTotalAsset: { period: string; v: number }[];
      totalDebtToTotalCapital: { period: string; v: number }[];
      totalRatio: { period: string; v: number }[];
    };
    quarterly: {
      cashRatio: { period: string; v: number }[];
      currentRatio: { period: string; v: number }[];
      ebitPerShare: { period: string; v: number }[];
      eps: { period: string; v: number }[];
      grossMargin: { period: string; v: number }[];
      longtermDebtTotalAsset: { period: string; v: number }[];
      longtermDebtTotalCapital: { period: string; v: number }[];
      longtermDebtTotalEquity: { period: string; v: number }[];
      netDebtToTotalCapital: { period: string; v: number }[];
      netDebtToTotalEquity: { period: string; v: number }[];
      netMargin: { period: string; v: number }[];
      operatingMargin: { period: string; v: number }[];
      pretaxMargin: { period: string; v: number }[];
      salesPerShare: { period: string; v: number }[];
      sgaToSale: { period: string; v: number }[];
      totalDebtToEquity: { period: string; v: number }[];
      totalDebtToTotalAsset: { period: string; v: number }[];
      totalDebtToTotalCapital: { period: string; v: number }[];
      totalRatio: { period: string; v: number }[];
    };
  };
  symbol: string;
}
